### ISSUE TITLE
Crash on startup because num_points is 255 before first touch

### ISSUE THREAD

**Issue by Hixie** [ardera/raspberrypi-fast-ts#2]
On my hardware (Pi 3B+) and software (Linux 5.4.72-v7+), the driver crashes on startup because the number of points it gets from the hardware causes it to overrun the events buffer. This seems to fix it for me, no idea if it's the right answer:

```patch
diff --git a/raspberrypi-fast-ts.c b/raspberrypi-fast-ts.c
index 0d1d051..fdf4c32 100644
--- a/raspberrypi-fast-ts.c
+++ b/raspberrypi-fast-ts.c
@@ -97,6 +97,12 @@ static int poll(struct ts *ts) {
 
     modified_ids = 0;
 
+    if (ts->regs.num_points == 0xff) {
+        // On some devices, this seems to indicate no touches have yet
+        // been detected. Ignore the rest of the data.
+        return 0;
+    }
+
     for (int i = 0; i < ts->regs.num_points; i++) {
         ok = read_into_regs(ts->i2c_fd, ts->slave_addr, point[i].xh, &ts->regs, 4);
         if (ok < 0) {
```

**Comment by ardera** [comment]
I don't know what the right answer is either. According to [this datasheet](https://www.displayfuture.com/Display/datasheet/controller/FT5x06.pdf) of a touchscreen controller chip used in earlier versions of the display, the the lowest 4 bits of the `num_points` / `TD_POINTS` register should unconditionally report the number of touches, at least after startup. Tough no part of the Raspberry Pi or this touchscreen driver actually waits for the touchscreen to boot, so maybe it's polling the ts too early. That'd also make sense because `0xFF` is kinda the "default" value you read from an I2C bus when noone is actually driving it.

I think your workaround works, `0xFF` should be treated just like `0`

**Comment by Hixie** [comment]
On my hardware it doesn't seem to boot until the first time it's touched, FWIW.

**Comment by ardera** [comment]
fixed (forgot to close this)
